<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\CompositeDataSource\Gpa;

use Atlas\Table\Table;

class GpaTable extends Table
{
    const NAME = 'gpas';

    const COLUMNS = [
        'student_fn' => [
            'name' => 'student_fn',
            'type' => 'VARCHAR',
            'size' => 10,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
        ],
        'student_ln' => [
            'name' => 'student_ln',
            'type' => 'VARCHAR',
            'size' => 10,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
        ],
        'gpa' => [
            'name' => 'gpa',
            'type' => 'DECIMAL',
            'size' => 4,
            'scale' => 3,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
    ];

    const COLUMN_NAMES = [
        'student_fn',
        'student_ln',
        'gpa',
    ];

    const COLUMN_DEFAULTS = [
        'student_fn' => null,
        'student_ln' => null,
        'gpa' => null,
    ];

    const PRIMARY_KEY = [
        'student_fn',
        'student_ln',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
