<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Bidibar;

use Atlas\Mapper\Record;

/**
 * @property mixed $bidibar_id INTEGER
 * @property mixed $bidifoo_id INTEGER
 * @property mixed $name VARCHAR(10)
 */
class BidibarFields extends Record
{
}
