<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Student;

use Atlas\Mapper\Record;

/**
 * @property mixed $student_fn VARCHAR(10)
 * @property mixed $student_ln VARCHAR(10)
 * @property mixed $degree_type CHAR(2)
 * @property mixed $degree_subject CHAR(4)
 */
class StudentFields extends Record
{
}
