<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Tag;

use Atlas\Mapper\Record;

/**
 * @property mixed $tag_id INTEGER
 * @property mixed $name VARCHAR(10) NOT NULL
 */
class TagFields extends Record
{
}
