<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Tag;

use Atlas\Table\Table;

class TagTable extends Table
{
    const NAME = 'tags';

    const COLUMNS = [
        'tag_id' => [
            'name' => 'tag_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
        ],
        'name' => [
            'name' => 'name',
            'type' => 'VARCHAR',
            'size' => 10,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
    ];

    const COLUMN_NAMES = [
        'tag_id',
        'name',
    ];

    const COLUMN_DEFAULTS = [
        'tag_id' => null,
        'name' => null,
    ];

    const PRIMARY_KEY = [
        'tag_id',
    ];

    const AUTOINC_COLUMN = 'tag_id';

    const AUTOINC_SEQUENCE = null;
}
