<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Bidibar\_generated;

use Atlas\Table\TableSelect;
use Atlas\Testing\DataSource\Bidibar\BidibarRow;

/**
 * @method ?BidibarRow fetchRow()
 * @method BidibarRow[] fetchRows()
 */
abstract class BidibarTableSelect_ extends TableSelect
{
}
