<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Comment\_generated;

use Atlas\Mapper\Mapper;
use Atlas\Testing\DataSource\Comment\CommentRecord;
use Atlas\Testing\DataSource\Comment\CommentRecordSet;
use Atlas\Testing\DataSource\Comment\CommentRelated;
use Atlas\Testing\DataSource\Comment\CommentSelect;
use Atlas\Testing\DataSource\Comment\CommentTable;

/**
 * @method CommentTable getTable()
 * @method ?CommentRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?CommentRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method CommentRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method CommentRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method CommentRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method CommentRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method CommentSelect select(array $whereEquals = [])
 * @method CommentRecord newRecord(array $fields = [])
 * @method CommentRecord[] newRecords(array $fieldSets)
 * @method CommentRecordSet newRecordSet(CommentRecord[] $records = [])
 * @method CommentRecord turnRowIntoRecord(CommentRow $row, array $loadRelated = [])
 * @method CommentRecord[] turnRowsIntoRecords(CommentRow[] $rows, array $loadRelated = [])
 */
abstract class Comment_ extends Mapper
{
    public const RECORD_CLASS = CommentRecord::CLASS;
    public const RECORD_SET_CLASS = CommentRecordSet::CLASS;
    public const RELATED_CLASS = CommentRelated::CLASS;
    public const SELECT_CLASS = CommentSelect::CLASS;
}
