<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Comment\_generated;

use Atlas\Mapper\RecordSet;
use Atlas\Testing\DataSource\Comment\CommentRecord;
use Atlas\Testing\DataSource\Comment\CommentRecordSet;

/**
 * @method __construct(CommentRecord[], callable $newRecordFactory)
 * @method CommentRecord offsetGet($offset)
 * @method CommentRecord appendNew(array $fields = [])
 * @method ?CommentRecord getOneBy(array $whereEquals)
 * @method CommentRecordSet getAllBy(array $whereEquals)
 * @method ?CommentRecord detachOneBy(array $whereEquals)
 * @method CommentRecordSet detachAllBy(array $whereEquals)
 * @method CommentRecordSet detachAll()
 * @method CommentRecordSet detachDeleted()
 */
abstract class CommentRecordSet_ extends RecordSet
{
}
