<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Author\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $author_id INTEGER
 * @property mixed $name VARCHAR(10) NOT NULL
 * @property \Atlas\Testing\DataSource\Reply\ReplyRecordSet $replies
 * @property \Atlas\Testing\DataSource\Thread\ThreadRecordSet $threads
 * @method \Atlas\Testing\DataSource\Author\AuthorRow getRow()
 */
abstract class AuthorRecord_ extends Record
{
}
