<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Author\_generated;

use Atlas\Table\TableSelect;
use Atlas\Testing\DataSource\Author\AuthorRow;

/**
 * @method ?AuthorRow fetchRow()
 * @method AuthorRow[] fetchRows()
 */
abstract class AuthorTableSelect_ extends TableSelect
{
}
