<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Tagging;

use Atlas\Mapper\Record;

/**
 * @property mixed $tagging_id INTEGER
 * @property mixed $thread_id INTEGER NOT NULL
 * @property mixed $tag_id INTEGER NOT NULL
 */
class TaggingFields extends Record
{
}
