<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Tagging;

/**
 * @property mixed $tagging_id INTEGER
 * @property mixed $thread_id INTEGER NOT NULL
 * @property mixed $tag_id INTEGER NOT NULL
 */
trait TaggingFields
{
}
