<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Tagging;

/**
 * @property mixed $tagging_id INTEGER
 * @property mixed $thread_id INTEGER
 * @property mixed $tag_id INTEGER
 * @property null|false|\Atlas\Testing\DataSource\Thread\ThreadRecord $thread
 * @property null|false|\Atlas\Testing\DataSource\Tag\TagRecord $tag
 */
trait TaggingFields
{
}
