<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Nopkey\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $name VARCHAR(255)
 * @property mixed $email VARCHAR(255)
 * @method \Atlas\Testing\DataSource\Nopkey\NopkeyRow getRow()
 */
abstract class NopkeyRecord_ extends Record
{
}
