<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Nopkey\_generated;

use Atlas\Table\TableSelect;
use Atlas\Testing\DataSource\Nopkey\NopkeyRow;

/**
 * @method ?NopkeyRow fetchRow()
 * @method NopkeyRow[] fetchRows()
 */
abstract class NopkeyTableSelect_ extends TableSelect
{
}
