<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\CompositeDataSource\Degree;

use Atlas\Mapper\Record;

/**
 * @property mixed $degree_type CHAR(2)
 * @property mixed $degree_subject CHAR(4)
 * @property mixed $title VARCHAR(50)
 */
class DegreeFields extends Record
{
}
