<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Video\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $video_id INTEGER
 * @property mixed $title VARCHAR(255)
 * @property mixed $url VARCHAR(255)
 * @property \Atlas\Testing\DataSource\Comment\CommentRecordSet $comments
 * @method \Atlas\Testing\DataSource\Video\VideoRow getRow()
 */
abstract class VideoRecord_ extends Record
{
}
