<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Video\_generated;

use Atlas\Mapper\Mapper;
use Atlas\Testing\DataSource\Video\VideoRecord;
use Atlas\Testing\DataSource\Video\VideoRecordSet;
use Atlas\Testing\DataSource\Video\VideoRelated;
use Atlas\Testing\DataSource\Video\VideoSelect;
use Atlas\Testing\DataSource\Video\VideoTable;

/**
 * @method VideoTable getTable()
 * @method ?VideoRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?VideoRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method VideoRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method VideoRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method VideoRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method VideoRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method VideoSelect select(array $whereEquals = [])
 * @method VideoRecord newRecord(array $fields = [])
 * @method VideoRecord[] newRecords(array $fieldSets)
 * @method VideoRecordSet newRecordSet(array $records = [])
 * @method VideoRecord turnRowIntoRecord(VideoRow $row, array $loadRelated = [])
 * @method VideoRecord[] turnRowsIntoRecords(array $rows, array $loadRelated = [])
 */
abstract class Video_ extends Mapper
{
    public const RECORD_CLASS = VideoRecord::CLASS;
    public const RECORD_SET_CLASS = VideoRecordSet::CLASS;
    public const RELATED_CLASS = VideoRelated::CLASS;
    public const SELECT_CLASS = VideoSelect::CLASS;
}
