<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Video\_generated;

use Atlas\Mapper\MapperEvents;

abstract class VideoEvents_ extends MapperEvents
{
}
