<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Video\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Testing\DataSource\Video\VideoRecord;
use Atlas\Testing\DataSource\Video\VideoRecordSet;

/**
 * @method ?VideoRecord fetchRecord()
 * @method VideoRecord[] fetchRecords()
 * @method VideoRecordSet fetchRecordSet()
 * @method ?VideoRow fetchRow()
 * @method VideoRow[] fetchRows()
 */
abstract class VideoSelect_ extends MapperSelect
{
}
