<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Author;

use Atlas\Mapper\Record;

/**
 * @property mixed $author_id INTEGER
 * @property mixed $name VARCHAR(10) NOT NULL
 */
class AuthorFields extends Record
{
}
