<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Author;

use Atlas\Table\Row;

/**
 * @property mixed $author_id INTEGER
 * @property mixed $name VARCHAR(10) NOT NULL
 */
class AuthorRow extends Row
{
    protected $cols = [
        'author_id' => null,
        'name' => null,
    ];
}
