<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Employee\_generated;

use Atlas\Table\TableSelect;
use Atlas\Testing\DataSource\Employee\EmployeeRow;

/**
 * @method ?EmployeeRow fetchRow()
 * @method EmployeeRow[] fetchRows()
 */
abstract class EmployeeTableSelect_ extends TableSelect
{
}
