<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Employee\_generated;

use Atlas\Mapper\RecordSet;
use Atlas\Testing\DataSource\Employee\EmployeeRecord;
use Atlas\Testing\DataSource\Employee\EmployeeRecordSet;

/**
 * @method __construct(EmployeeRecord[], callable $newRecordFactory)
 * @method EmployeeRecord offsetGet($offset)
 * @method EmployeeRecord appendNew(array $fields = [])
 * @method ?EmployeeRecord getOneBy(array $whereEquals)
 * @method EmployeeRecordSet getAllBy(array $whereEquals)
 * @method ?EmployeeRecord detachOneBy(array $whereEquals)
 * @method EmployeeRecordSet detachAllBy(array $whereEquals)
 * @method EmployeeRecordSet detachAll()
 * @method EmployeeRecordSet detachDeleted()
 */
abstract class EmployeeRecordSet_ extends RecordSet
{
}
