<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Comment;

use Atlas\Table\Table;

/**
 * @method CommentTableRow|null fetchRow($primaryVal)
 * @method CommentTableRow[] fetchRows(array $primaryVals)
 * @method CommentTableSelect select(array $whereEquals = [])
 * @method CommentTableRow newRow(array $cols = [])
 * @method CommentTableRow newSelectedRow(array $cols)
 */
class CommentTable extends Table
{
    const NAME = 'comments';

    const COLUMNS = [
        'comment_id' => [
            'name' => 'comment_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
        ],
        'related_type' => [
            'name' => 'related_type',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
        'related_id' => [
            'name' => 'related_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
        'body' => [
            'name' => 'body',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
    ];

    const COLUMN_NAMES = [
        'comment_id',
        'related_type',
        'related_id',
        'body',
    ];

    const COLUMN_DEFAULTS = [
        'comment_id' => null,
        'related_type' => null,
        'related_id' => null,
        'body' => null,
    ];

    const PRIMARY_KEY = [
        'comment_id',
    ];

    const AUTOINC_COLUMN = 'comment_id';

    const AUTOINC_SEQUENCE = null;
}
