<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Comment;

use Atlas\Mapper\Record;

/**
 * @property mixed $comment_id INTEGER
 * @property mixed $related_type VARCHAR(255)
 * @property mixed $related_id INTEGER
 * @property mixed $body TEXT
 */
class CommentFields extends Record
{
}
