<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Employee;

use Atlas\Table\Table;

/**
 * @method EmployeeTableRow|null fetchRow($primaryVal)
 * @method EmployeeTableRow[] fetchRows(array $primaryVals)
 * @method EmployeeTableSelect select(array $whereEquals = [])
 * @method EmployeeTableRow newRow(array $cols = [])
 * @method EmployeeTableRow newSelectedRow(array $cols)
 */
class EmployeeTable extends Table
{
    const NAME = 'employee';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
        ],
        'name' => [
            'name' => 'name',
            'type' => 'VARCHAR',
            'size' => 10,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
        'building' => [
            'name' => 'building',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
        'floor' => [
            'name' => 'floor',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'name',
        'building',
        'floor',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'name' => null,
        'building' => null,
        'floor' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
