<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Employee;

use Atlas\Mapper\Record;

/**
 * @property mixed $id INTEGER
 * @property mixed $name VARCHAR(10) NOT NULL
 * @property mixed $building INTEGER
 * @property mixed $floor INTEGER
 */
class EmployeeFields extends Record
{
}
