<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Employee;

class EmployeeTable extends _generated\EmployeeTable_
{
}
