<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Reply;

use Atlas\Table\Table;

/**
 * @method ReplyTableRow|null fetchRow($primaryVal)
 * @method ReplyTableRow[] fetchRows(array $primaryVals)
 * @method ReplyTableSelect select(array $whereEquals = [])
 * @method ReplyTableRow newRow(array $cols = [])
 * @method ReplyTableRow newSelectedRow(array $cols)
 */
class ReplyTable extends Table
{
    const NAME = 'replies';

    const COLUMNS = [
        'reply_id' => [
            'name' => 'reply_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
        ],
        'thread_id' => [
            'name' => 'thread_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
        'author_id' => [
            'name' => 'author_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
        'body' => [
            'name' => 'body',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
    ];

    const COLUMN_NAMES = [
        'reply_id',
        'thread_id',
        'author_id',
        'body',
    ];

    const COLUMN_DEFAULTS = [
        'reply_id' => null,
        'thread_id' => null,
        'author_id' => null,
        'body' => null,
    ];

    const PRIMARY_KEY = [
        'reply_id',
    ];

    const AUTOINC_COLUMN = 'reply_id';

    const AUTOINC_SEQUENCE = null;
}
