<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Reply;

use Atlas\Table\Row;

/**
 * @property mixed $reply_id INTEGER
 * @property mixed $thread_id INTEGER NOT NULL
 * @property mixed $author_id INTEGER NOT NULL
 * @property mixed $body TEXT
 */
class ReplyRow extends Row
{
    protected $cols = [
        'reply_id' => null,
        'thread_id' => null,
        'author_id' => null,
        'body' => null,
    ];
}
