<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Nopkey;

class NopkeyRow extends _generated\NopkeyRow_
{
}
