<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\CompositeDataSource\Course\_generated;

use Atlas\Table\TableSelect;
use Atlas\Testing\CompositeDataSource\Course\CourseRow;

/**
 * @method ?CourseRow fetchRow()
 * @method CourseRow[] fetchRows()
 */
abstract class CourseTableSelect_ extends TableSelect
{
}
