<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\CompositeDataSource\Student\_generated;

use Atlas\Table\TableSelect;
use Atlas\Testing\CompositeDataSource\Student\StudentRow;

/**
 * @method ?StudentRow fetchRow()
 * @method StudentRow[] fetchRows()
 */
abstract class StudentTableSelect_ extends TableSelect
{
}
