<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\CompositeDataSource\Student\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $student_fn VARCHAR(10)
 * @property mixed $student_ln VARCHAR(10)
 * @property mixed $degree_type CHAR(2)
 * @property mixed $degree_subject CHAR(4)
 * @method \Atlas\Testing\CompositeDataSource\Student\StudentRow getRow()
 */
abstract class StudentRecord_ extends Record
{
}
