<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\CompositeDataSource\Student\_generated;

use Atlas\Table\TableEvents;

abstract class StudentTableEvents_ extends TableEvents
{
}
