<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\CompositeDataSource\Enrollment;

use Atlas\Mapper\Record;

/**
 * @property mixed $student_fn VARCHAR(10)
 * @property mixed $student_ln VARCHAR(10)
 * @property mixed $course_subject CHAR(4)
 * @property mixed $course_number INT
 * @property mixed $grade INT
 * @property mixed $points INT
 */
class EnrollmentFields extends Record
{
}
