<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\CompositeDataSource\Enrollment;

class EnrollmentRow extends _generated\EnrollmentRow_
{
}
