<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\CompositeDataSource\Enrollment;

/**
 * @property mixed $student_fn VARCHAR(10)
 * @property mixed $student_ln VARCHAR(10)
 * @property mixed $course_subject CHAR(4)
 * @property mixed $course_number INT
 * @property mixed $grade INT
 * @property mixed $points INT
 * @property null|false|\Atlas\Testing\CompositeDataSource\Course\CourseRecord $course
 * @property null|false|\Atlas\Testing\CompositeDataSource\Student\StudentRecord $student
 */
trait EnrollmentFields
{
}
