<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\CompositeDataSource\Enrollment;

use Atlas\Table\Row;

/**
 * @property mixed $student_fn VARCHAR(10)
 * @property mixed $student_ln VARCHAR(10)
 * @property mixed $course_subject CHAR(4)
 * @property mixed $course_number INT
 * @property mixed $grade INT
 * @property mixed $points INT
 */
class EnrollmentRow extends Row
{
    protected $cols = [
        'student_fn' => null,
        'student_ln' => null,
        'course_subject' => null,
        'course_number' => null,
        'grade' => null,
        'points' => null,
    ];
}
