<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Video;

use Atlas\Mapper\Record;

/**
 * @property mixed $video_id INTEGER
 * @property mixed $title VARCHAR(255)
 * @property mixed $url VARCHAR(255)
 */
class VideoFields extends Record
{
}
