<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Video;

use Atlas\Table\Table;

class VideoTable extends Table
{
    const NAME = 'videos';

    const COLUMNS = [
        'video_id' => [
            'name' => 'video_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
        ],
        'title' => [
            'name' => 'title',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
        'url' => [
            'name' => 'url',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
    ];

    const COLUMN_NAMES = [
        'video_id',
        'title',
        'url',
    ];

    const COLUMN_DEFAULTS = [
        'video_id' => null,
        'title' => null,
        'url' => null,
    ];

    const PRIMARY_KEY = [
        'video_id',
    ];

    const AUTOINC_COLUMN = 'video_id';

    const AUTOINC_SEQUENCE = null;
}
