<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Video;

use Atlas\Table\Row;

/**
 * @property mixed $video_id INTEGER
 * @property mixed $title VARCHAR(255)
 * @property mixed $url VARCHAR(255)
 */
class VideoRow extends Row
{
    protected $cols = [
        'video_id' => null,
        'title' => null,
        'url' => null,
    ];
}
