<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\CompositeDataSource\Student;

use Atlas\Table\Table;

class StudentTable extends Table
{
    const NAME = 'students';

    const COLUMNS = [
        'student_fn' => [
            'name' => 'student_fn',
            'type' => 'VARCHAR',
            'size' => 10,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
        ],
        'student_ln' => [
            'name' => 'student_ln',
            'type' => 'VARCHAR',
            'size' => 10,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
        ],
        'degree_type' => [
            'name' => 'degree_type',
            'type' => 'CHAR',
            'size' => 2,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
        'degree_subject' => [
            'name' => 'degree_subject',
            'type' => 'CHAR',
            'size' => 4,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
    ];

    const COLUMN_NAMES = [
        'student_fn',
        'student_ln',
        'degree_type',
        'degree_subject',
    ];

    const COLUMN_DEFAULTS = [
        'student_fn' => null,
        'student_ln' => null,
        'degree_type' => null,
        'degree_subject' => null,
    ];

    const PRIMARY_KEY = [
        'student_fn',
        'student_ln',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
