<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Tag\_generated;

use Atlas\Mapper\RecordSet;
use Atlas\Testing\DataSource\Tag\TagRecord;
use Atlas\Testing\DataSource\Tag\TagRecordSet;

/**
 * @method __construct(TagRecord[], callable $newRecordFactory)
 * @method TagRecord offsetGet($offset)
 * @method TagRecord appendNew(array $fields = [])
 * @method ?TagRecord getOneBy(array $whereEquals)
 * @method TagRecordSet getAllBy(array $whereEquals)
 * @method ?TagRecord detachOneBy(array $whereEquals)
 * @method TagRecordSet detachAllBy(array $whereEquals)
 * @method TagRecordSet detachAll()
 * @method TagRecordSet detachDeleted()
 */
abstract class TagRecordSet_ extends RecordSet
{
}
