<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Tag\_generated;

use Atlas\Mapper\Record;

/**
 * @property mixed $tag_id INTEGER
 * @property mixed $name VARCHAR(10) NOT NULL
 * @property \Atlas\Testing\DataSource\Tagging\TaggingRecordSet $taggings
 * @method \Atlas\Testing\DataSource\Tag\TagRow getRow()
 */
abstract class TagRecord_ extends Record
{
}
