<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Tag\_generated;

use Atlas\Table\TableSelect;
use Atlas\Testing\DataSource\Tag\TagRow;

/**
 * @method ?TagRow fetchRow()
 * @method TagRow[] fetchRows()
 */
abstract class TagTableSelect_ extends TableSelect
{
}
