<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Tagging\_generated;

use Atlas\Mapper\RecordSet;
use Atlas\Testing\DataSource\Tagging\TaggingRecord;
use Atlas\Testing\DataSource\Tagging\TaggingRecordSet;

/**
 * @method __construct(TaggingRecord[], callable $newRecordFactory)
 * @method TaggingRecord offsetGet($offset)
 * @method TaggingRecord appendNew(array $fields = [])
 * @method ?TaggingRecord getOneBy(array $whereEquals)
 * @method TaggingRecordSet getAllBy(array $whereEquals)
 * @method ?TaggingRecord detachOneBy(array $whereEquals)
 * @method TaggingRecordSet detachAllBy(array $whereEquals)
 * @method TaggingRecordSet detachAll()
 * @method TaggingRecordSet detachDeleted()
 */
abstract class TaggingRecordSet_ extends RecordSet
{
}
