<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Post\_generated;

use Atlas\Mapper\Mapper;
use Atlas\Testing\DataSource\Post\PostRecord;
use Atlas\Testing\DataSource\Post\PostRecordSet;
use Atlas\Testing\DataSource\Post\PostRelated;
use Atlas\Testing\DataSource\Post\PostSelect;
use Atlas\Testing\DataSource\Post\PostTable;

/**
 * @method PostTable getTable()
 * @method ?PostRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?PostRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method PostRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method PostRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method PostRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method PostRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method PostSelect select(array $whereEquals = [])
 * @method PostRecord newRecord(array $fields = [])
 * @method PostRecord[] newRecords(array $fieldSets)
 * @method PostRecordSet newRecordSet(PostRecord[] $records = [])
 * @method PostRecord turnRowIntoRecord(PostRow $row, array $loadRelated = [])
 * @method PostRecord[] turnRowsIntoRecords(PostRow[] $rows, array $loadRelated = [])
 */
abstract class Post_ extends Mapper
{
    public const RECORD_CLASS = PostRecord::CLASS;
    public const RECORD_SET_CLASS = PostRecordSet::CLASS;
    public const RELATED_CLASS = PostRelated::CLASS;
    public const SELECT_CLASS = PostSelect::CLASS;
}
