<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Post\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Testing\DataSource\Post\PostRecord;
use Atlas\Testing\DataSource\Post\PostRecordSet;

/**
 * @method ?PostRecord fetchRecord()
 * @method PostRecord[] fetchRecords()
 * @method PostRecordSet fetchRecordSet()
 * @method ?PostRow fetchRow()
 * @method PostRow[] fetchRows()
 */
abstract class PostSelect_ extends MapperSelect
{
}
