<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Post\_generated;

use Atlas\Table\TableSelect;
use Atlas\Testing\DataSource\Post\PostRow;

/**
 * @method ?PostRow fetchRow()
 * @method PostRow[] fetchRows()
 */
abstract class PostTableSelect_ extends TableSelect
{
}
