<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Page;

/**
 * @property mixed $page_id INTEGER
 * @property mixed $title VARCHAR(255)
 * @property mixed $body TEXT
 */
trait PageFields
{
}
