<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Page;

use Atlas\Table\Row;

/**
 * @property mixed $page_id INTEGER
 * @property mixed $title VARCHAR(255)
 * @property mixed $body TEXT
 */
class PageRow extends Row
{
    protected $cols = [
        'page_id' => null,
        'title' => null,
        'body' => null,
    ];
}
