<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Page;

use Atlas\Mapper\Record;

/**
 * @property mixed $page_id INTEGER
 * @property mixed $title VARCHAR(255)
 * @property mixed $body TEXT
 */
class PageFields extends Record
{
}
