<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Bidifoo;

use Atlas\Table\Row;

/**
 * @property mixed $bidifoo_id INTEGER
 * @property mixed $bidibar_id INTEGER
 * @property mixed $name VARCHAR(10)
 */
class BidifooRow extends Row
{
    protected $cols = [
        'bidifoo_id' => null,
        'bidibar_id' => null,
        'name' => null,
    ];
}
