<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Bidifoo;

class BidifooTable extends _generated\BidifooTable_
{
}
