<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\CompositeDataSource\Degree\_generated;

use Atlas\Mapper\RecordSet;
use Atlas\Testing\CompositeDataSource\Degree\DegreeRecord;
use Atlas\Testing\CompositeDataSource\Degree\DegreeRecordSet;

/**
 * @method __construct(DegreeRecord[], callable $newRecordFactory)
 * @method DegreeRecord offsetGet($offset)
 * @method DegreeRecord appendNew(array $fields = [])
 * @method ?DegreeRecord getOneBy(array $whereEquals)
 * @method DegreeRecordSet getAllBy(array $whereEquals)
 * @method ?DegreeRecord detachOneBy(array $whereEquals)
 * @method DegreeRecordSet detachAllBy(array $whereEquals)
 * @method DegreeRecordSet detachAll()
 * @method DegreeRecordSet detachDeleted()
 */
abstract class DegreeRecordSet_ extends RecordSet
{
}
