<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Reply\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Testing\DataSource\Reply\ReplyRecord;
use Atlas\Testing\DataSource\Reply\ReplyRecordSet;

/**
 * @method ?ReplyRecord fetchRecord()
 * @method ReplyRecord[] fetchRecords()
 * @method ReplyRecordSet fetchRecordSet()
 * @method ?ReplyRow fetchRow()
 * @method ReplyRow[] fetchRows()
 */
abstract class ReplySelect_ extends MapperSelect
{
}
