<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Reply\_generated;

use Atlas\Mapper\RecordSet;
use Atlas\Testing\DataSource\Reply\ReplyRecord;
use Atlas\Testing\DataSource\Reply\ReplyRecordSet;

/**
 * @method __construct(ReplyRecord[], callable $newRecordFactory)
 * @method ReplyRecord offsetGet($offset)
 * @method ReplyRecord appendNew(array $fields = [])
 * @method ?ReplyRecord getOneBy(array $whereEquals)
 * @method ReplyRecordSet getAllBy(array $whereEquals)
 * @method ?ReplyRecord detachOneBy(array $whereEquals)
 * @method ReplyRecordSet detachAllBy(array $whereEquals)
 * @method ReplyRecordSet detachAll()
 * @method ReplyRecordSet detachDeleted()
 */
abstract class ReplyRecordSet_ extends RecordSet
{
}
