<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Summary\_generated;

use Atlas\Mapper\RecordSet;
use Atlas\Testing\DataSource\Summary\SummaryRecord;
use Atlas\Testing\DataSource\Summary\SummaryRecordSet;

/**
 * @method __construct(SummaryRecord[], callable $newRecordFactory)
 * @method SummaryRecord offsetGet($offset)
 * @method SummaryRecord appendNew(array $fields = [])
 * @method ?SummaryRecord getOneBy(array $whereEquals)
 * @method SummaryRecordSet getAllBy(array $whereEquals)
 * @method ?SummaryRecord detachOneBy(array $whereEquals)
 * @method SummaryRecordSet detachAllBy(array $whereEquals)
 * @method SummaryRecordSet detachAll()
 * @method SummaryRecordSet detachDeleted()
 */
abstract class SummaryRecordSet_ extends RecordSet
{
}
