<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Summary\_generated;

use Atlas\Table\TableSelect;
use Atlas\Testing\DataSource\Summary\SummaryRow;

/**
 * @method ?SummaryRow fetchRow()
 * @method SummaryRow[] fetchRows()
 */
abstract class SummaryTableSelect_ extends TableSelect
{
}
