<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Summary\_generated;

use Atlas\Mapper\Mapper;
use Atlas\Testing\DataSource\Summary\SummaryRecord;
use Atlas\Testing\DataSource\Summary\SummaryRecordSet;
use Atlas\Testing\DataSource\Summary\SummaryRelated;
use Atlas\Testing\DataSource\Summary\SummarySelect;
use Atlas\Testing\DataSource\Summary\SummaryTable;

/**
 * @method SummaryTable getTable()
 * @method ?SummaryRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?SummaryRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method SummaryRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method SummaryRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method SummaryRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method SummaryRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method SummarySelect select(array $whereEquals = [])
 * @method SummaryRecord newRecord(array $fields = [])
 * @method SummaryRecord[] newRecords(array $fieldSets)
 * @method SummaryRecordSet newRecordSet(SummaryRecord[] $records = [])
 * @method SummaryRecord turnRowIntoRecord(SummaryRow $row, array $loadRelated = [])
 * @method SummaryRecord[] turnRowsIntoRecords(SummaryRow[] $rows, array $loadRelated = [])
 */
abstract class Summary_ extends Mapper
{
    public const RECORD_CLASS = SummaryRecord::CLASS;
    public const RECORD_SET_CLASS = SummaryRecordSet::CLASS;
    public const RELATED_CLASS = SummaryRelated::CLASS;
    public const SELECT_CLASS = SummarySelect::CLASS;
}
