<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\CompositeDataSource\Gpa\_generated;

use Atlas\Table\TableSelect;
use Atlas\Testing\CompositeDataSource\Gpa\GpaRow;

/**
 * @method ?GpaRow fetchRow()
 * @method GpaRow[] fetchRows()
 */
abstract class GpaTableSelect_ extends TableSelect
{
}
