<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Degree;

use Atlas\Table\Table;

class DegreeTable extends Table
{
    const NAME = 'degrees';

    const COLUMNS = [
        'degree_type' => [
            'name' => 'degree_type',
            'type' => 'CHAR',
            'size' => 2,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
        ],
        'degree_subject' => [
            'name' => 'degree_subject',
            'type' => 'CHAR',
            'size' => 4,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => true,
        ],
        'title' => [
            'name' => 'title',
            'type' => 'VARCHAR',
            'size' => 50,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
        ],
    ];

    const COLUMN_NAMES = [
        'degree_type',
        'degree_subject',
        'title',
    ];

    const COLUMN_DEFAULTS = [
        'degree_type' => null,
        'degree_subject' => null,
        'title' => null,
    ];

    const PRIMARY_KEY = [
        'degree_type',
        'degree_subject',
    ];

    const AUTOINC_COLUMN = null;

    const AUTOINC_SEQUENCE = null;
}
