<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Post;

use Atlas\Table\Row;

/**
 * @property mixed $post_id INTEGER
 * @property mixed $subj VARCHAR(255)
 * @property mixed $body TEXT
 */
class PostRow extends Row
{
    protected $cols = [
        'post_id' => null,
        'subj' => null,
        'body' => null,
    ];
}
