<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Post;

use Atlas\Mapper\Record;

/**
 * @property mixed $post_id INTEGER
 * @property mixed $subj VARCHAR(255)
 * @property mixed $body TEXT
 */
class PostFields extends Record
{
}
