<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Summary;

use Atlas\Table\Row;

/**
 * @property mixed $summary_id INTEGER
 * @property mixed $thread_id INTEGER NOT NULL
 * @property mixed $reply_count INTEGER NOT NULL
 * @property mixed $view_count INTEGER NOT NULL
 */
class SummaryRow extends Row
{
    protected $cols = [
        'summary_id' => null,
        'thread_id' => null,
        'reply_count' => '0',
        'view_count' => '0',
    ];
}
