<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Summary;

/**
 * @property mixed $summary_id INTEGER
 * @property mixed $thread_id INTEGER NOT NULL
 * @property mixed $reply_count INTEGER NOT NULL
 * @property mixed $view_count INTEGER NOT NULL
 */
trait SummaryFields
{
}
