<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Summary;

use Atlas\Mapper\Record;

/**
 * @property mixed $summary_id INTEGER
 * @property mixed $thread_id INTEGER NOT NULL
 * @property mixed $reply_count INTEGER NOT NULL
 * @property mixed $view_count INTEGER NOT NULL
 */
class SummaryFields extends Record
{
}
