<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Page\_generated;

use Atlas\Mapper\MapperSelect;
use Atlas\Testing\DataSource\Page\PageRecord;
use Atlas\Testing\DataSource\Page\PageRecordSet;

/**
 * @method ?PageRecord fetchRecord()
 * @method PageRecord[] fetchRecords()
 * @method PageRecordSet fetchRecordSet()
 * @method ?PageRow fetchRow()
 * @method PageRow[] fetchRows()
 */
abstract class PageSelect_ extends MapperSelect
{
}
