<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Page\_generated;

use Atlas\Mapper\Mapper;
use Atlas\Testing\DataSource\Page\PageRecord;
use Atlas\Testing\DataSource\Page\PageRecordSet;
use Atlas\Testing\DataSource\Page\PageRelated;
use Atlas\Testing\DataSource\Page\PageSelect;
use Atlas\Testing\DataSource\Page\PageTable;

/**
 * @method PageTable getTable()
 * @method ?PageRecord fetchRecord(mixed $primaryVal, array $loadRelated = [])
 * @method ?PageRecord fetchRecordBy(array $whereEquals, array $loadRelated = [])
 * @method PageRecord[] fetchRecords(array $primaryVals, array $loadRelated = [])
 * @method PageRecord[] fetchRecordsBy(array $whereEquals, array $loadRelated = [])
 * @method PageRecordSet fetchRecordSet(array $primaryVals, array $loadRelated = [])
 * @method PageRecordSet fetchRecordSetBy(array $whereEquals, array $loadRelated = [])
 * @method PageSelect select(array $whereEquals = [])
 * @method PageRecord newRecord(array $fields = [])
 * @method PageRecord[] newRecords(array $fieldSets)
 * @method PageRecordSet newRecordSet(PageRecord[] $records = [])
 * @method PageRecord turnRowIntoRecord(PageRow $row, array $loadRelated = [])
 * @method PageRecord[] turnRowsIntoRecords(PageRow[] $rows, array $loadRelated = [])
 */
abstract class Page_ extends Mapper
{
    public const RECORD_CLASS = PageRecord::CLASS;
    public const RECORD_SET_CLASS = PageRecordSet::CLASS;
    public const RELATED_CLASS = PageRelated::CLASS;
    public const SELECT_CLASS = PageSelect::CLASS;
}
