<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Page\_generated;

use Atlas\Mapper\RecordSet;
use Atlas\Testing\DataSource\Page\PageRecord;
use Atlas\Testing\DataSource\Page\PageRecordSet;

/**
 * @method __construct(PageRecord[], callable $newRecordFactory)
 * @method PageRecord offsetGet($offset)
 * @method PageRecord appendNew(array $fields = [])
 * @method ?PageRecord getOneBy(array $whereEquals)
 * @method PageRecordSet getAllBy(array $whereEquals)
 * @method ?PageRecord detachOneBy(array $whereEquals)
 * @method PageRecordSet detachAllBy(array $whereEquals)
 * @method PageRecordSet detachAll()
 * @method PageRecordSet detachDeleted()
 */
abstract class PageRecordSet_ extends RecordSet
{
}
