<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Page\_generated;

use Atlas\Table\TableSelect;
use Atlas\Testing\DataSource\Page\PageRow;

/**
 * @method ?PageRow fetchRow()
 * @method PageRow[] fetchRows()
 */
abstract class PageTableSelect_ extends TableSelect
{
}
