<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Testing\DataSource\Course;

use Atlas\Mapper\Record;

/**
 * @property mixed $course_subject CHAR(4)
 * @property mixed $course_number INT
 * @property mixed $title VARCHAR(20)
 */
class CourseFields extends Record
{
}
