<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Thread\_generated;

use Atlas\Table\TableEvents;

abstract class ThreadTableEvents_ extends TableEvents
{
}
