<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Atlas\Testing\DataSource\Thread\_generated;

use Atlas\Table\TableSelect;
use Atlas\Testing\DataSource\Thread\ThreadRow;

/**
 * @method ?ThreadRow fetchRow()
 * @method ThreadRow[] fetchRows()
 */
abstract class ThreadTableSelect_ extends TableSelect
{
}
